version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rest-market-db
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: