spring.application.name=rest-market-api
spring.datasource.url=jdbc:postgresql://localhost:5432/market_db
spring.datasource.username=market_user
spring.datasource.password=market_password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

spring.sql.init.data-locations=classpath:init.sql
spring.sql.init.mode=always
